version: "3.1"
networks:
  net1:

services:
  db:
    build: test_env/db
    container_name: bookit-db-main
    networks:
      net1:
        aliases:
          - db-main

  app:
    build:
      context: .
      args:
        HOST: 0.0.0.0
        PORT: 8081
      dockerfile: Dockerfile
    container_name: bookit_app

    depends_on:
      - db
    networks:
      net1:
        aliases:
          - app
    volumes:
    - ./:/app
